package com.yangcy.gofish.data.database

import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import platform.Foundation.NSHomeDirectory

actual fun getDatabaseBuilder(): RoomDatabase.Builder<AppDatabase> {
    val dbFilePath = NSHomeDirectory() + "/fish_guide_database.db"
    return Room.databaseBuilder<AppDatabase>(
        name = dbFilePath
    )
}

// AppDatabaseConstructor is generated by Room
